### ISSUE TITLE
Mysql reconnection errors on NA and EU

### ISSUE THREAD

**Issue by phtrivier** [AirVantage/av-sched#6]
Seen this week-end in logly ; this seem to have been caused by calls from av-accounts to av-sched's APIS. The calls resulted in 500 errors from av-sched, which apparently were not properly handled by av-accounts. 

The root Exception was this : 

~~~
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: 
The last packet successfully received from the server was 293,872,399 milliseconds ago.  
The last packet sent successfully to the server was 293,872,401 milliseconds ago. is longer
 than the server configured value of 'wait_timeout'. 
You should consider either expiring and/or testing connection validity before 
use in your application, increasing the server configured values for client timeouts, 
or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
~~~

This might be caused by the fact that connections are very rarely used by av-sched ?

This should be solvable by setting "autoReconnect" to "true" on the DataSource, if this is caused by jdbc queries from DbUtils.

If this is caused by jbcd queries 'hidden' inside quartz, we would have to modify its configuration (it does not reuse the same DataSource.)

Full typicall stack : 
~~~

[qtp671467883-13 ] o.q.impl.jdbcjobstore.JobStoreTX Couldn't rollback jdbc connection. No operations allowed after connection closed.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
 at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source) ~[na:na]
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
 at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
 at com.mysql.jdbc.Util.handleNewInstance(Util.java:389) ~[av-sched.jar:na]
 at com.mysql.jdbc.Util.getInstance(Util.java:372) ~[av-sched.jar:na]
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:958) ~[av-sched.jar:na]
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937) ~[av-sched.jar:na]
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[av-sched.jar:na]
 at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872) ~[av-sched.jar:na]
 at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1236) ~[av-sched.jar:na]
 at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1231) ~[av-sched.jar:na]
 at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4574) ~[av-sched.jar:na]
 at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:855) ~[av-sched.jar:na]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
 at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
 at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73) ~[av-sched.jar:na]
 at com.sun.proxy.$Proxy3.rollback(Unknown Source) ~[na:na]
 at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3650) [av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3809) [av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93) [av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3723) [av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.JobStoreSupport.getTriggersForJob(JobStoreSupport.java:2127) [av-sched.jar:na]
 at org.quartz.core.QuartzScheduler.getTriggersOfJob(QuartzScheduler.java:1476) [av-sched.jar:na]
 at org.quartz.core.QuartzScheduler.deleteJob(QuartzScheduler.java:989) [av-sched.jar:na]
 at org.quartz.impl.StdScheduler.deleteJob(StdScheduler.java:301) [av-sched.jar:na]
 at net.airvantage.sched.services.JobServiceImpl.scheduleQuarzJob(JobServiceImpl.java:105) [av-sched.jar:na]
 at net.airvantage.sched.services.JobServiceImpl.scheduleJob(JobServiceImpl.java:45) [av-sched.jar:na]
 at net.airvantage.sched.app.JobDefServlet.doPost(JobDefServlet.java:59) [av-sched.jar:na]
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [av-sched.jar:na]
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [av-sched.jar:na]
 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [av-sched.jar:na]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) [av-sched.jar:na]
 at net.airvantage.sched.app.SchedSecretFilter.doFilter(SchedSecretFilter.java:38) [av-sched.jar:na]
 at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [av-sched.jar:na]
 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [av-sched.jar:na]
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [av-sched.jar:na]
 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [av-sched.jar:na]
 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [av-sched.jar:na]
 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [av-sched.jar:na]
 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [av-sched.jar:na]
 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [av-sched.jar:na]
 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [av-sched.jar:na]
 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [av-sched.jar:na]
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [av-sched.jar:na]
 at org.eclipse.jetty.server.Server.handle(Server.java:485) [av-sched.jar:na]
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290) [av-sched.jar:na]
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [av-sched.jar:na]
 at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [av-sched.jar:na]
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606) [av-sched.jar:na]
 at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535) [av-sched.jar:na]
 at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 293,872,399 milliseconds ago.  The last packet sent successfully to the server was 293,872,401 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_45]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_45]
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_45]
 at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45]
 at com.mysql.jdbc.Util.handleNewInstance(Util.java:389) ~[av-sched.jar:na]
 at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038) ~[av-sched.jar:na]
 at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3609) ~[av-sched.jar:na]
 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2417) ~[av-sched.jar:na]
 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[av-sched.jar:na]
 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531) ~[av-sched.jar:na]
 at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4852) ~[av-sched.jar:na]
 at com.mchange.v2.c3p0.impl.NewProxyConnection.setAutoCommit(NewProxyConnection.java:881) ~[av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.setAutoCommit(AttributeRestoringConnectionInvocationHandler.java:98) ~[av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:66) ~[av-sched.jar:na]
 at com.sun.proxy.$Proxy3.setAutoCommit(Unknown Source) ~[na:na]
 at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:799) [av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71) [av-sched.jar:na]
 at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3784) [av-sched.jar:na]
 ... 32 common frames omitted
Caused by: java.net.SocketException: Broken pipe
 at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_45]
 at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_45]
 at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[na:1.8.0_45]
 at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_45]
 at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_45]
 at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3591) ~[av-sched.jar:na]
 ... 43 common frames omitted
~~~

**Comment by phtrivier** [comment]
Might habe been fixed by #7 , will need release.
